name: RPM build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_rpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create source archive
        run: >
          cd .. 
          && tar -czf python-bytecode.tar.gz bytecode
          && mv python-bytecode.tar.gz bytecode/.github/actions/buildrpm

      - name: Build RPM package
        id: rpm
        uses: ./.github/actions/buildrpm

      - name: Upload RPM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-rpm
          path: ${{ github.workspace }}
